"""empty message

Revision ID: 286ae0faac2f
Revises: 1ff56cdd15a5
Create Date: 2023-08-17 09:33:34.493270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286ae0faac2f'
down_revision = '1ff56cdd15a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_messages')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.TIMESTAMP(),
               nullable=True)

    op.create_table('_alembic_tmp_messages',
    sa.Column('message_id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=True),
    sa.Column('receiver_id', sa.INTEGER(), nullable=True),
    sa.Column('content', sa.VARCHAR(), nullable=True),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.user_id'], name='fk_messages_receiver_id_users'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], name='fk_messages_sender_id_users'),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###
